### ISSUE TITLE
Fan templating broken

### ISSUE THREAD

**Issue by hubertgruber** [CoMPaTech/esphome_c1101#6]
In Home Assistant 2022.2, the fan templating is broken, as there is now a requirement for a percentage. See https://developers.home-assistant.io/docs/core/entity/fan/#deprecated-properties.

**Comment by CoMPaTech** [comment]
I'll have a look at how to rewrite it to a better and more reproducable thing

**Comment by CoMPaTech** [comment]
Hi @hubertgruber - I recently moved everything and didn't realise not using the templating broke that way. I tried rewriting it already but there is a snag. It seems esphome / fan is not able to 'take' speed settings from something external.

I'll leave my rewrite of the esp yaml below - if you are only using the fan-component (i.e. skip setting high for 10/20/30 minutes etc.) and not have the intent to 'read' whatever the physical switches are sending you can get away with it.

The below code is based off having the custom switches as already included in the original version.
```
fan:
  - platform: speed
    speed_count: 3
    output: mech_vent
    name: "Mechanische ventilatie"
    restore_mode: NO_RESTORE
    on_turn_on:
    - logger.log: "Fan Turned On, setting to 10min!"
    - switch.turn_on: fansendt1
        
    on_turn_off:
    - logger.log: "Fan Turned Off, setting to low speed!"
    - switch.turn_on: fansendlow
        

output:
  - platform: template
    id: mech_vent
    type: float
    write_action:
      - if:
          condition:
            lambda: return ((state == 0));
          then:
            # action for off
            - logger.log: "Fan set to low speed"
            - switch.turn_on: fansendlow
      - if:
          condition:
            lambda: return ((state > 0) && (state < .34));
          then:
            # action for low
            - logger.log: "Fan set to low speed"
            - switch.turn_on: fansendlow
      - if:
          condition:
            lambda: return ((state > .34) && (state < .67));
          then:
            # action for medium
            - logger.log: "Fan set to medium speed"
            - switch.turn_on: fansendmedium
                
      - if:
          condition:
            lambda: return ((state == 1));
          then:
            # action for high
            - logger.log: "Fan set to high speed"
            - switch.turn_on: fansendhigh
```

If it doesn't (re)build for you on homeassistant itself (using the esphome addon) - it works for me using this on the top
```
esphome:
  name: {yournamehere}
  platform: ESP8266
  board: d1_mini_lite
  libraries:
    - SPI
    - https://github.com/CoMPaTech/esphome_itho.git
    - Ticker
  includes:
    - ITHO/fancontrol.h
```
